### ISSUE TITLE
where  is utils.aug

### ISSUE THREAD

**Issue by 24werewolf** [eragonruan/refinenet-image-segmentation#2]
Under the utils folder, I didn't find the utils.aug file

**Comment by eragonruan** [comment]
？[augmentation.py](https://github.com/eragonruan/refinenet-image-segmentation/blob/master/utils/augmentation.py)

**Comment by eragonruan** [comment]
@24werewolf I was try to read data directly from the disk without convert it into tfrecord. so there remains some code with bug not solved. I will move this part to other branch soon.
